// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Core user messages
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	BankAccounts  []*BankAccount         `protobuf:"bytes,7,rep,name=bank_accounts,json=bankAccounts,proto3" json:"bank_accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetBankAccounts() []*BankAccount {
	if x != nil {
		return x.BankAccounts
	}
	return nil
}

// User request/response messages
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// User preferences messages
type UserPreferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Timezone      string                 `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	DarkMode      bool                   `protobuf:"varint,4,opt,name=dark_mode,json=darkMode,proto3" json:"dark_mode,omitempty"`
	Budget        float64                `protobuf:"fixed64,5,opt,name=budget,proto3" json:"budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPreferences) Reset() {
	*x = UserPreferences{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferences) ProtoMessage() {}

func (x *UserPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferences.ProtoReflect.Descriptor instead.
func (*UserPreferences) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserPreferences) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UserPreferences) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UserPreferences) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UserPreferences) GetDarkMode() bool {
	if x != nil {
		return x.DarkMode
	}
	return false
}

func (x *UserPreferences) GetBudget() float64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

type CreateUserPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	DarkMode      bool                   `protobuf:"varint,5,opt,name=dark_mode,json=darkMode,proto3" json:"dark_mode,omitempty"`
	Budget        float64                `protobuf:"fixed64,6,opt,name=budget,proto3" json:"budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserPreferencesRequest) Reset() {
	*x = CreateUserPreferencesRequest{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserPreferencesRequest) ProtoMessage() {}

func (x *CreateUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*CreateUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *CreateUserPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserPreferencesRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateUserPreferencesRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CreateUserPreferencesRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreateUserPreferencesRequest) GetDarkMode() bool {
	if x != nil {
		return x.DarkMode
	}
	return false
}

func (x *CreateUserPreferencesRequest) GetBudget() float64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

type GetUserPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPreferencesRequest) Reset() {
	*x = GetUserPreferencesRequest{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPreferencesRequest) ProtoMessage() {}

func (x *GetUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateUserPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	DarkMode      bool                   `protobuf:"varint,5,opt,name=dark_mode,json=darkMode,proto3" json:"dark_mode,omitempty"`
	Budget        float64                `protobuf:"fixed64,6,opt,name=budget,proto3" json:"budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPreferencesRequest) Reset() {
	*x = UpdateUserPreferencesRequest{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPreferencesRequest) ProtoMessage() {}

func (x *UpdateUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserPreferencesRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateUserPreferencesRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UpdateUserPreferencesRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UpdateUserPreferencesRequest) GetDarkMode() bool {
	if x != nil {
		return x.DarkMode
	}
	return false
}

func (x *UpdateUserPreferencesRequest) GetBudget() float64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

type DeleteUserPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserPreferencesRequest) Reset() {
	*x = DeleteUserPreferencesRequest{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserPreferencesRequest) ProtoMessage() {}

func (x *DeleteUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteUserPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserPreferencesResponse) Reset() {
	*x = DeleteUserPreferencesResponse{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserPreferencesResponse) ProtoMessage() {}

func (x *DeleteUserPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserPreferencesResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUserPreferencesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Notification preferences messages
type NotificationPreferences struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NotificationsEnabled bool                   `protobuf:"varint,1,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	SmsNotifications     bool                   `protobuf:"varint,2,opt,name=sms_notifications,json=smsNotifications,proto3" json:"sms_notifications,omitempty"`
	PushNotifications    bool                   `protobuf:"varint,3,opt,name=push_notifications,json=pushNotifications,proto3" json:"push_notifications,omitempty"`
	EmailNotifications   bool                   `protobuf:"varint,4,opt,name=email_notifications,json=emailNotifications,proto3" json:"email_notifications,omitempty"`
	NotificationTypes    []string               `protobuf:"bytes,5,rep,name=notification_types,json=notificationTypes,proto3" json:"notification_types,omitempty"` // ["large_transaction", "budget_alert", "savings_goal", "weekly_summary", etc]
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NotificationPreferences) Reset() {
	*x = NotificationPreferences{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPreferences) ProtoMessage() {}

func (x *NotificationPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPreferences.ProtoReflect.Descriptor instead.
func (*NotificationPreferences) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *NotificationPreferences) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

func (x *NotificationPreferences) GetSmsNotifications() bool {
	if x != nil {
		return x.SmsNotifications
	}
	return false
}

func (x *NotificationPreferences) GetPushNotifications() bool {
	if x != nil {
		return x.PushNotifications
	}
	return false
}

func (x *NotificationPreferences) GetEmailNotifications() bool {
	if x != nil {
		return x.EmailNotifications
	}
	return false
}

func (x *NotificationPreferences) GetNotificationTypes() []string {
	if x != nil {
		return x.NotificationTypes
	}
	return nil
}

type CreateNotificationPreferencesRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotificationsEnabled bool                   `protobuf:"varint,2,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	SmsNotifications     bool                   `protobuf:"varint,3,opt,name=sms_notifications,json=smsNotifications,proto3" json:"sms_notifications,omitempty"`
	PushNotifications    bool                   `protobuf:"varint,4,opt,name=push_notifications,json=pushNotifications,proto3" json:"push_notifications,omitempty"`
	EmailNotifications   bool                   `protobuf:"varint,5,opt,name=email_notifications,json=emailNotifications,proto3" json:"email_notifications,omitempty"`
	NotificationTypes    []string               `protobuf:"bytes,6,rep,name=notification_types,json=notificationTypes,proto3" json:"notification_types,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateNotificationPreferencesRequest) Reset() {
	*x = CreateNotificationPreferencesRequest{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationPreferencesRequest) ProtoMessage() {}

func (x *CreateNotificationPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationPreferencesRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *CreateNotificationPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateNotificationPreferencesRequest) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

func (x *CreateNotificationPreferencesRequest) GetSmsNotifications() bool {
	if x != nil {
		return x.SmsNotifications
	}
	return false
}

func (x *CreateNotificationPreferencesRequest) GetPushNotifications() bool {
	if x != nil {
		return x.PushNotifications
	}
	return false
}

func (x *CreateNotificationPreferencesRequest) GetEmailNotifications() bool {
	if x != nil {
		return x.EmailNotifications
	}
	return false
}

func (x *CreateNotificationPreferencesRequest) GetNotificationTypes() []string {
	if x != nil {
		return x.NotificationTypes
	}
	return nil
}

type GetNotificationPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationPreferencesRequest) Reset() {
	*x = GetNotificationPreferencesRequest{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationPreferencesRequest) ProtoMessage() {}

func (x *GetNotificationPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetNotificationPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateNotificationPreferencesRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotificationsEnabled bool                   `protobuf:"varint,2,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	SmsNotifications     bool                   `protobuf:"varint,3,opt,name=sms_notifications,json=smsNotifications,proto3" json:"sms_notifications,omitempty"`
	PushNotifications    bool                   `protobuf:"varint,4,opt,name=push_notifications,json=pushNotifications,proto3" json:"push_notifications,omitempty"`
	EmailNotifications   bool                   `protobuf:"varint,5,opt,name=email_notifications,json=emailNotifications,proto3" json:"email_notifications,omitempty"`
	NotificationTypes    []string               `protobuf:"bytes,6,rep,name=notification_types,json=notificationTypes,proto3" json:"notification_types,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateNotificationPreferencesRequest) Reset() {
	*x = UpdateNotificationPreferencesRequest{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationPreferencesRequest) ProtoMessage() {}

func (x *UpdateNotificationPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationPreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateNotificationPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateNotificationPreferencesRequest) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

func (x *UpdateNotificationPreferencesRequest) GetSmsNotifications() bool {
	if x != nil {
		return x.SmsNotifications
	}
	return false
}

func (x *UpdateNotificationPreferencesRequest) GetPushNotifications() bool {
	if x != nil {
		return x.PushNotifications
	}
	return false
}

func (x *UpdateNotificationPreferencesRequest) GetEmailNotifications() bool {
	if x != nil {
		return x.EmailNotifications
	}
	return false
}

func (x *UpdateNotificationPreferencesRequest) GetNotificationTypes() []string {
	if x != nil {
		return x.NotificationTypes
	}
	return nil
}

type DeleteNotificationPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationPreferencesRequest) Reset() {
	*x = DeleteNotificationPreferencesRequest{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationPreferencesRequest) ProtoMessage() {}

func (x *DeleteNotificationPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationPreferencesRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotificationPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteNotificationPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteNotificationPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationPreferencesResponse) Reset() {
	*x = DeleteNotificationPreferencesResponse{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationPreferencesResponse) ProtoMessage() {}

func (x *DeleteNotificationPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationPreferencesResponse.ProtoReflect.Descriptor instead.
func (*DeleteNotificationPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteNotificationPreferencesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Bank account messages
type BankAccount struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlaidAccountId string                 `protobuf:"bytes,3,opt,name=plaid_account_id,json=plaidAccountId,proto3" json:"plaid_account_id,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Balance        float64                `protobuf:"fixed64,6,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency       string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	IsActive       bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BankAccount) Reset() {
	*x = BankAccount{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankAccount) ProtoMessage() {}

func (x *BankAccount) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankAccount.ProtoReflect.Descriptor instead.
func (*BankAccount) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *BankAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BankAccount) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BankAccount) GetPlaidAccountId() string {
	if x != nil {
		return x.PlaidAccountId
	}
	return ""
}

func (x *BankAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BankAccount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BankAccount) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *BankAccount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BankAccount) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *BankAccount) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BankAccount) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type LinkBankAccountRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlaidAccessToken string                 `protobuf:"bytes,2,opt,name=plaid_access_token,json=plaidAccessToken,proto3" json:"plaid_access_token,omitempty"`
	PlaidAccountId   string                 `protobuf:"bytes,3,opt,name=plaid_account_id,json=plaidAccountId,proto3" json:"plaid_account_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LinkBankAccountRequest) Reset() {
	*x = LinkBankAccountRequest{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkBankAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkBankAccountRequest) ProtoMessage() {}

func (x *LinkBankAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkBankAccountRequest.ProtoReflect.Descriptor instead.
func (*LinkBankAccountRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *LinkBankAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LinkBankAccountRequest) GetPlaidAccessToken() string {
	if x != nil {
		return x.PlaidAccessToken
	}
	return ""
}

func (x *LinkBankAccountRequest) GetPlaidAccountId() string {
	if x != nil {
		return x.PlaidAccountId
	}
	return ""
}

type ListBankAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBankAccountsRequest) Reset() {
	*x = ListBankAccountsRequest{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBankAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBankAccountsRequest) ProtoMessage() {}

func (x *ListBankAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBankAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListBankAccountsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *ListBankAccountsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListBankAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*BankAccount         `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBankAccountsResponse) Reset() {
	*x = ListBankAccountsResponse{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBankAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBankAccountsResponse) ProtoMessage() {}

func (x *ListBankAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBankAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListBankAccountsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

func (x *ListBankAccountsResponse) GetAccounts() []*BankAccount {
	if x != nil {
		return x.Accounts
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x126\n" +
	"\rbank_accounts\x18\a \x03(\v2\x11.user.BankAccountR\fbankAccounts\"e\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"u\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9a\x01\n" +
	"\x0fUserPreferences\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1b\n" +
	"\tdark_mode\x18\x04 \x01(\bR\bdarkMode\x12\x16\n" +
	"\x06budget\x18\x05 \x01(\x01R\x06budget\"\xc0\x01\n" +
	"\x1cCreateUserPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1b\n" +
	"\tdark_mode\x18\x05 \x01(\bR\bdarkMode\x12\x16\n" +
	"\x06budget\x18\x06 \x01(\x01R\x06budget\"4\n" +
	"\x19GetUserPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xc0\x01\n" +
	"\x1cUpdateUserPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1b\n" +
	"\tdark_mode\x18\x05 \x01(\bR\bdarkMode\x12\x16\n" +
	"\x06budget\x18\x06 \x01(\x01R\x06budget\"7\n" +
	"\x1cDeleteUserPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"9\n" +
	"\x1dDeleteUserPreferencesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8a\x02\n" +
	"\x17NotificationPreferences\x123\n" +
	"\x15notifications_enabled\x18\x01 \x01(\bR\x14notificationsEnabled\x12+\n" +
	"\x11sms_notifications\x18\x02 \x01(\bR\x10smsNotifications\x12-\n" +
	"\x12push_notifications\x18\x03 \x01(\bR\x11pushNotifications\x12/\n" +
	"\x13email_notifications\x18\x04 \x01(\bR\x12emailNotifications\x12-\n" +
	"\x12notification_types\x18\x05 \x03(\tR\x11notificationTypes\"\xb0\x02\n" +
	"$CreateNotificationPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x123\n" +
	"\x15notifications_enabled\x18\x02 \x01(\bR\x14notificationsEnabled\x12+\n" +
	"\x11sms_notifications\x18\x03 \x01(\bR\x10smsNotifications\x12-\n" +
	"\x12push_notifications\x18\x04 \x01(\bR\x11pushNotifications\x12/\n" +
	"\x13email_notifications\x18\x05 \x01(\bR\x12emailNotifications\x12-\n" +
	"\x12notification_types\x18\x06 \x03(\tR\x11notificationTypes\"<\n" +
	"!GetNotificationPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xb0\x02\n" +
	"$UpdateNotificationPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x123\n" +
	"\x15notifications_enabled\x18\x02 \x01(\bR\x14notificationsEnabled\x12+\n" +
	"\x11sms_notifications\x18\x03 \x01(\bR\x10smsNotifications\x12-\n" +
	"\x12push_notifications\x18\x04 \x01(\bR\x11pushNotifications\x12/\n" +
	"\x13email_notifications\x18\x05 \x01(\bR\x12emailNotifications\x12-\n" +
	"\x12notification_types\x18\x06 \x03(\tR\x11notificationTypes\"?\n" +
	"$DeleteNotificationPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"A\n" +
	"%DeleteNotificationPreferencesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xd1\x02\n" +
	"\vBankAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12(\n" +
	"\x10plaid_account_id\x18\x03 \x01(\tR\x0eplaidAccountId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x18\n" +
	"\abalance\x18\x06 \x01(\x01R\abalance\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x89\x01\n" +
	"\x16LinkBankAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\x12plaid_access_token\x18\x02 \x01(\tR\x10plaidAccessToken\x12(\n" +
	"\x10plaid_account_id\x18\x03 \x01(\tR\x0eplaidAccountId\"2\n" +
	"\x17ListBankAccountsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"I\n" +
	"\x18ListBankAccountsResponse\x12-\n" +
	"\baccounts\x18\x01 \x03(\v2\x11.user.BankAccountR\baccounts2\x88\t\n" +
	"\vUserService\x121\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\n" +
	".user.User\x12+\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\n" +
	".user.User\x121\n" +
	"\n" +
	"UpdateUser\x12\x17.user.UpdateUserRequest\x1a\n" +
	".user.User\x12?\n" +
	"\n" +
	"DeleteUser\x12\x17.user.DeleteUserRequest\x1a\x18.user.DeleteUserResponse\x12R\n" +
	"\x15CreateUserPreferences\x12\".user.CreateUserPreferencesRequest\x1a\x15.user.UserPreferences\x12L\n" +
	"\x12GetUserPreferences\x12\x1f.user.GetUserPreferencesRequest\x1a\x15.user.UserPreferences\x12R\n" +
	"\x15UpdateUserPreferences\x12\".user.UpdateUserPreferencesRequest\x1a\x15.user.UserPreferences\x12`\n" +
	"\x15DeleteUserPreferences\x12\".user.DeleteUserPreferencesRequest\x1a#.user.DeleteUserPreferencesResponse\x12j\n" +
	"\x1dCreateNotificationPreferences\x12*.user.CreateNotificationPreferencesRequest\x1a\x1d.user.NotificationPreferences\x12d\n" +
	"\x1aGetNotificationPreferences\x12'.user.GetNotificationPreferencesRequest\x1a\x1d.user.NotificationPreferences\x12j\n" +
	"\x1dUpdateNotificationPreferences\x12*.user.UpdateNotificationPreferencesRequest\x1a\x1d.user.NotificationPreferences\x12x\n" +
	"\x1dDeleteNotificationPreferences\x12*.user.DeleteNotificationPreferencesRequest\x1a+.user.DeleteNotificationPreferencesResponse\x12B\n" +
	"\x0fLinkBankAccount\x12\x1c.user.LinkBankAccountRequest\x1a\x11.user.BankAccount\x12Q\n" +
	"\x10ListBankAccounts\x12\x1d.user.ListBankAccountsRequest\x1a\x1e.user.ListBankAccountsResponseB\x1eZ\x1cuntether/services/user/protob\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_user_proto_goTypes = []any{
	(*User)(nil),                                  // 0: user.User
	(*CreateUserRequest)(nil),                     // 1: user.CreateUserRequest
	(*GetUserRequest)(nil),                        // 2: user.GetUserRequest
	(*UpdateUserRequest)(nil),                     // 3: user.UpdateUserRequest
	(*DeleteUserRequest)(nil),                     // 4: user.DeleteUserRequest
	(*DeleteUserResponse)(nil),                    // 5: user.DeleteUserResponse
	(*UserPreferences)(nil),                       // 6: user.UserPreferences
	(*CreateUserPreferencesRequest)(nil),          // 7: user.CreateUserPreferencesRequest
	(*GetUserPreferencesRequest)(nil),             // 8: user.GetUserPreferencesRequest
	(*UpdateUserPreferencesRequest)(nil),          // 9: user.UpdateUserPreferencesRequest
	(*DeleteUserPreferencesRequest)(nil),          // 10: user.DeleteUserPreferencesRequest
	(*DeleteUserPreferencesResponse)(nil),         // 11: user.DeleteUserPreferencesResponse
	(*NotificationPreferences)(nil),               // 12: user.NotificationPreferences
	(*CreateNotificationPreferencesRequest)(nil),  // 13: user.CreateNotificationPreferencesRequest
	(*GetNotificationPreferencesRequest)(nil),     // 14: user.GetNotificationPreferencesRequest
	(*UpdateNotificationPreferencesRequest)(nil),  // 15: user.UpdateNotificationPreferencesRequest
	(*DeleteNotificationPreferencesRequest)(nil),  // 16: user.DeleteNotificationPreferencesRequest
	(*DeleteNotificationPreferencesResponse)(nil), // 17: user.DeleteNotificationPreferencesResponse
	(*BankAccount)(nil),                           // 18: user.BankAccount
	(*LinkBankAccountRequest)(nil),                // 19: user.LinkBankAccountRequest
	(*ListBankAccountsRequest)(nil),               // 20: user.ListBankAccountsRequest
	(*ListBankAccountsResponse)(nil),              // 21: user.ListBankAccountsResponse
	(*timestamppb.Timestamp)(nil),                 // 22: google.protobuf.Timestamp
}
var file_user_proto_depIdxs = []int32{
	22, // 0: user.User.created_at:type_name -> google.protobuf.Timestamp
	22, // 1: user.User.updated_at:type_name -> google.protobuf.Timestamp
	18, // 2: user.User.bank_accounts:type_name -> user.BankAccount
	22, // 3: user.BankAccount.created_at:type_name -> google.protobuf.Timestamp
	22, // 4: user.BankAccount.updated_at:type_name -> google.protobuf.Timestamp
	18, // 5: user.ListBankAccountsResponse.accounts:type_name -> user.BankAccount
	1,  // 6: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	2,  // 7: user.UserService.GetUser:input_type -> user.GetUserRequest
	3,  // 8: user.UserService.UpdateUser:input_type -> user.UpdateUserRequest
	4,  // 9: user.UserService.DeleteUser:input_type -> user.DeleteUserRequest
	7,  // 10: user.UserService.CreateUserPreferences:input_type -> user.CreateUserPreferencesRequest
	8,  // 11: user.UserService.GetUserPreferences:input_type -> user.GetUserPreferencesRequest
	9,  // 12: user.UserService.UpdateUserPreferences:input_type -> user.UpdateUserPreferencesRequest
	10, // 13: user.UserService.DeleteUserPreferences:input_type -> user.DeleteUserPreferencesRequest
	13, // 14: user.UserService.CreateNotificationPreferences:input_type -> user.CreateNotificationPreferencesRequest
	14, // 15: user.UserService.GetNotificationPreferences:input_type -> user.GetNotificationPreferencesRequest
	15, // 16: user.UserService.UpdateNotificationPreferences:input_type -> user.UpdateNotificationPreferencesRequest
	16, // 17: user.UserService.DeleteNotificationPreferences:input_type -> user.DeleteNotificationPreferencesRequest
	19, // 18: user.UserService.LinkBankAccount:input_type -> user.LinkBankAccountRequest
	20, // 19: user.UserService.ListBankAccounts:input_type -> user.ListBankAccountsRequest
	0,  // 20: user.UserService.CreateUser:output_type -> user.User
	0,  // 21: user.UserService.GetUser:output_type -> user.User
	0,  // 22: user.UserService.UpdateUser:output_type -> user.User
	5,  // 23: user.UserService.DeleteUser:output_type -> user.DeleteUserResponse
	6,  // 24: user.UserService.CreateUserPreferences:output_type -> user.UserPreferences
	6,  // 25: user.UserService.GetUserPreferences:output_type -> user.UserPreferences
	6,  // 26: user.UserService.UpdateUserPreferences:output_type -> user.UserPreferences
	11, // 27: user.UserService.DeleteUserPreferences:output_type -> user.DeleteUserPreferencesResponse
	12, // 28: user.UserService.CreateNotificationPreferences:output_type -> user.NotificationPreferences
	12, // 29: user.UserService.GetNotificationPreferences:output_type -> user.NotificationPreferences
	12, // 30: user.UserService.UpdateNotificationPreferences:output_type -> user.NotificationPreferences
	17, // 31: user.UserService.DeleteNotificationPreferences:output_type -> user.DeleteNotificationPreferencesResponse
	18, // 32: user.UserService.LinkBankAccount:output_type -> user.BankAccount
	21, // 33: user.UserService.ListBankAccounts:output_type -> user.ListBankAccountsResponse
	20, // [20:34] is the sub-list for method output_type
	6,  // [6:20] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
