// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: plaid.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLinkTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkTokenRequest) Reset() {
	*x = CreateLinkTokenRequest{}
	mi := &file_plaid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkTokenRequest) ProtoMessage() {}

func (x *CreateLinkTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkTokenRequest) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLinkTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateLinkTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkToken     string                 `protobuf:"bytes,1,opt,name=link_token,json=linkToken,proto3" json:"link_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkTokenResponse) Reset() {
	*x = CreateLinkTokenResponse{}
	mi := &file_plaid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkTokenResponse) ProtoMessage() {}

func (x *CreateLinkTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateLinkTokenResponse) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLinkTokenResponse) GetLinkToken() string {
	if x != nil {
		return x.LinkToken
	}
	return ""
}

type ExchangePublicTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicToken   string                 `protobuf:"bytes,1,opt,name=public_token,json=publicToken,proto3" json:"public_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangePublicTokenRequest) Reset() {
	*x = ExchangePublicTokenRequest{}
	mi := &file_plaid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangePublicTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangePublicTokenRequest) ProtoMessage() {}

func (x *ExchangePublicTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangePublicTokenRequest.ProtoReflect.Descriptor instead.
func (*ExchangePublicTokenRequest) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangePublicTokenRequest) GetPublicToken() string {
	if x != nil {
		return x.PublicToken
	}
	return ""
}

type ExchangePublicTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangePublicTokenResponse) Reset() {
	*x = ExchangePublicTokenResponse{}
	mi := &file_plaid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangePublicTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangePublicTokenResponse) ProtoMessage() {}

func (x *ExchangePublicTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangePublicTokenResponse.ProtoReflect.Descriptor instead.
func (*ExchangePublicTokenResponse) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangePublicTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ExchangePublicTokenResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type GetAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsRequest) Reset() {
	*x = GetAccountsRequest{}
	mi := &file_plaid_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsRequest) ProtoMessage() {}

func (x *GetAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsRequest.ProtoReflect.Descriptor instead.
func (*GetAccountsRequest) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountsRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Subtype       string                 `protobuf:"bytes,4,opt,name=subtype,proto3" json:"subtype,omitempty"`
	Mask          string                 `protobuf:"bytes,5,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_plaid_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{5}
}

func (x *Account) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Account) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

func (x *Account) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

type GetAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsResponse) Reset() {
	*x = GetAccountsResponse{}
	mi := &file_plaid_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsResponse) ProtoMessage() {}

func (x *GetAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsResponse.ProtoReflect.Descriptor instead.
func (*GetAccountsResponse) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_plaid_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{7}
}

func (x *GetBalanceRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type Balance struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Available       string                 `protobuf:"bytes,1,opt,name=available,proto3" json:"available,omitempty"`
	Current         string                 `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`
	Limit           string                 `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	IsoCurrencyCode string                 `protobuf:"bytes,4,opt,name=iso_currency_code,json=isoCurrencyCode,proto3" json:"iso_currency_code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_plaid_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{8}
}

func (x *Balance) GetAvailable() string {
	if x != nil {
		return x.Available
	}
	return ""
}

func (x *Balance) GetCurrent() string {
	if x != nil {
		return x.Current
	}
	return ""
}

func (x *Balance) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

func (x *Balance) GetIsoCurrencyCode() string {
	if x != nil {
		return x.IsoCurrencyCode
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_plaid_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{9}
}

func (x *GetBalanceResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

var File_plaid_proto protoreflect.FileDescriptor

const file_plaid_proto_rawDesc = "" +
	"\n" +
	"\vplaid.proto\x12\x05proto\"1\n" +
	"\x16CreateLinkTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x17CreateLinkTokenResponse\x12\x1d\n" +
	"\n" +
	"link_token\x18\x01 \x01(\tR\tlinkToken\"?\n" +
	"\x1aExchangePublicTokenRequest\x12!\n" +
	"\fpublic_token\x18\x01 \x01(\tR\vpublicToken\"Y\n" +
	"\x1bExchangePublicTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\"7\n" +
	"\x12GetAccountsRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"~\n" +
	"\aAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\asubtype\x18\x04 \x01(\tR\asubtype\x12\x12\n" +
	"\x04mask\x18\x05 \x01(\tR\x04mask\"A\n" +
	"\x13GetAccountsResponse\x12*\n" +
	"\baccounts\x18\x01 \x03(\v2\x0e.proto.AccountR\baccounts\"U\n" +
	"\x11GetBalanceRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"\x83\x01\n" +
	"\aBalance\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\tR\tavailable\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\tR\acurrent\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\tR\x05limit\x12*\n" +
	"\x11iso_currency_code\x18\x04 \x01(\tR\x0fisoCurrencyCode\">\n" +
	"\x12GetBalanceResponse\x12(\n" +
	"\abalance\x18\x01 \x01(\v2\x0e.proto.BalanceR\abalance2\xc7\x02\n" +
	"\fPlaidService\x12P\n" +
	"\x0fCreateLinkToken\x12\x1d.proto.CreateLinkTokenRequest\x1a\x1e.proto.CreateLinkTokenResponse\x12\\\n" +
	"\x13ExchangePublicToken\x12!.proto.ExchangePublicTokenRequest\x1a\".proto.ExchangePublicTokenResponse\x12D\n" +
	"\vGetAccounts\x12\x19.proto.GetAccountsRequest\x1a\x1a.proto.GetAccountsResponse\x12A\n" +
	"\n" +
	"GetBalance\x12\x18.proto.GetBalanceRequest\x1a\x19.proto.GetBalanceResponseB5Z3github.com/cgallagher/Untether/services/plaid/protob\x06proto3"

var (
	file_plaid_proto_rawDescOnce sync.Once
	file_plaid_proto_rawDescData []byte
)

func file_plaid_proto_rawDescGZIP() []byte {
	file_plaid_proto_rawDescOnce.Do(func() {
		file_plaid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plaid_proto_rawDesc), len(file_plaid_proto_rawDesc)))
	})
	return file_plaid_proto_rawDescData
}

var file_plaid_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_plaid_proto_goTypes = []any{
	(*CreateLinkTokenRequest)(nil),      // 0: proto.CreateLinkTokenRequest
	(*CreateLinkTokenResponse)(nil),     // 1: proto.CreateLinkTokenResponse
	(*ExchangePublicTokenRequest)(nil),  // 2: proto.ExchangePublicTokenRequest
	(*ExchangePublicTokenResponse)(nil), // 3: proto.ExchangePublicTokenResponse
	(*GetAccountsRequest)(nil),          // 4: proto.GetAccountsRequest
	(*Account)(nil),                     // 5: proto.Account
	(*GetAccountsResponse)(nil),         // 6: proto.GetAccountsResponse
	(*GetBalanceRequest)(nil),           // 7: proto.GetBalanceRequest
	(*Balance)(nil),                     // 8: proto.Balance
	(*GetBalanceResponse)(nil),          // 9: proto.GetBalanceResponse
}
var file_plaid_proto_depIdxs = []int32{
	5, // 0: proto.GetAccountsResponse.accounts:type_name -> proto.Account
	8, // 1: proto.GetBalanceResponse.balance:type_name -> proto.Balance
	0, // 2: proto.PlaidService.CreateLinkToken:input_type -> proto.CreateLinkTokenRequest
	2, // 3: proto.PlaidService.ExchangePublicToken:input_type -> proto.ExchangePublicTokenRequest
	4, // 4: proto.PlaidService.GetAccounts:input_type -> proto.GetAccountsRequest
	7, // 5: proto.PlaidService.GetBalance:input_type -> proto.GetBalanceRequest
	1, // 6: proto.PlaidService.CreateLinkToken:output_type -> proto.CreateLinkTokenResponse
	3, // 7: proto.PlaidService.ExchangePublicToken:output_type -> proto.ExchangePublicTokenResponse
	6, // 8: proto.PlaidService.GetAccounts:output_type -> proto.GetAccountsResponse
	9, // 9: proto.PlaidService.GetBalance:output_type -> proto.GetBalanceResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_plaid_proto_init() }
func file_plaid_proto_init() {
	if File_plaid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plaid_proto_rawDesc), len(file_plaid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plaid_proto_goTypes,
		DependencyIndexes: file_plaid_proto_depIdxs,
		MessageInfos:      file_plaid_proto_msgTypes,
	}.Build()
	File_plaid_proto = out.File
	file_plaid_proto_goTypes = nil
	file_plaid_proto_depIdxs = nil
}
