// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: plaid.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLinkTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkTokenRequest) Reset() {
	*x = CreateLinkTokenRequest{}
	mi := &file_plaid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkTokenRequest) ProtoMessage() {}

func (x *CreateLinkTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkTokenRequest) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLinkTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateLinkTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkToken     string                 `protobuf:"bytes,1,opt,name=link_token,json=linkToken,proto3" json:"link_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkTokenResponse) Reset() {
	*x = CreateLinkTokenResponse{}
	mi := &file_plaid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkTokenResponse) ProtoMessage() {}

func (x *CreateLinkTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateLinkTokenResponse) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLinkTokenResponse) GetLinkToken() string {
	if x != nil {
		return x.LinkToken
	}
	return ""
}

type ExchangePublicTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicToken   string                 `protobuf:"bytes,1,opt,name=public_token,json=publicToken,proto3" json:"public_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangePublicTokenRequest) Reset() {
	*x = ExchangePublicTokenRequest{}
	mi := &file_plaid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangePublicTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangePublicTokenRequest) ProtoMessage() {}

func (x *ExchangePublicTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangePublicTokenRequest.ProtoReflect.Descriptor instead.
func (*ExchangePublicTokenRequest) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangePublicTokenRequest) GetPublicToken() string {
	if x != nil {
		return x.PublicToken
	}
	return ""
}

type ExchangePublicTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangePublicTokenResponse) Reset() {
	*x = ExchangePublicTokenResponse{}
	mi := &file_plaid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangePublicTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangePublicTokenResponse) ProtoMessage() {}

func (x *ExchangePublicTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangePublicTokenResponse.ProtoReflect.Descriptor instead.
func (*ExchangePublicTokenResponse) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangePublicTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ExchangePublicTokenResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type GetAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsRequest) Reset() {
	*x = GetAccountsRequest{}
	mi := &file_plaid_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsRequest) ProtoMessage() {}

func (x *GetAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsRequest.ProtoReflect.Descriptor instead.
func (*GetAccountsRequest) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountsRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type BankAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Subtype       string                 `protobuf:"bytes,4,opt,name=subtype,proto3" json:"subtype,omitempty"`
	Mask          string                 `protobuf:"bytes,5,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankAccount) Reset() {
	*x = BankAccount{}
	mi := &file_plaid_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankAccount) ProtoMessage() {}

func (x *BankAccount) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankAccount.ProtoReflect.Descriptor instead.
func (*BankAccount) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{5}
}

func (x *BankAccount) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BankAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BankAccount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BankAccount) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

func (x *BankAccount) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

type GetAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*BankAccount         `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsResponse) Reset() {
	*x = GetAccountsResponse{}
	mi := &file_plaid_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsResponse) ProtoMessage() {}

func (x *GetAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsResponse.ProtoReflect.Descriptor instead.
func (*GetAccountsResponse) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountsResponse) GetAccounts() []*BankAccount {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_plaid_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{7}
}

func (x *GetBalanceRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_plaid_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plaid_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_plaid_proto_rawDescGZIP(), []int{8}
}

func (x *GetBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_plaid_proto protoreflect.FileDescriptor

const file_plaid_proto_rawDesc = "" +
	"\n" +
	"\vplaid.proto\x12\x05plaid\"1\n" +
	"\x16CreateLinkTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x17CreateLinkTokenResponse\x12\x1d\n" +
	"\n" +
	"link_token\x18\x01 \x01(\tR\tlinkToken\"?\n" +
	"\x1aExchangePublicTokenRequest\x12!\n" +
	"\fpublic_token\x18\x01 \x01(\tR\vpublicToken\"Y\n" +
	"\x1bExchangePublicTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\"7\n" +
	"\x12GetAccountsRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\x82\x01\n" +
	"\vBankAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\asubtype\x18\x04 \x01(\tR\asubtype\x12\x12\n" +
	"\x04mask\x18\x05 \x01(\tR\x04mask\"E\n" +
	"\x13GetAccountsResponse\x12.\n" +
	"\baccounts\x18\x01 \x03(\v2\x12.plaid.BankAccountR\baccounts\"U\n" +
	"\x11GetBalanceRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\".\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance2\xc7\x02\n" +
	"\fPlaidService\x12P\n" +
	"\x0fCreateLinkToken\x12\x1d.plaid.CreateLinkTokenRequest\x1a\x1e.plaid.CreateLinkTokenResponse\x12\\\n" +
	"\x13ExchangePublicToken\x12!.plaid.ExchangePublicTokenRequest\x1a\".plaid.ExchangePublicTokenResponse\x12D\n" +
	"\vGetAccounts\x12\x19.plaid.GetAccountsRequest\x1a\x1a.plaid.GetAccountsResponse\x12A\n" +
	"\n" +
	"GetBalance\x12\x18.plaid.GetBalanceRequest\x1a\x19.plaid.GetBalanceResponseB\x1fZ\x1duntether/services/plaid/protob\x06proto3"

var (
	file_plaid_proto_rawDescOnce sync.Once
	file_plaid_proto_rawDescData []byte
)

func file_plaid_proto_rawDescGZIP() []byte {
	file_plaid_proto_rawDescOnce.Do(func() {
		file_plaid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plaid_proto_rawDesc), len(file_plaid_proto_rawDesc)))
	})
	return file_plaid_proto_rawDescData
}

var file_plaid_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_plaid_proto_goTypes = []any{
	(*CreateLinkTokenRequest)(nil),      // 0: plaid.CreateLinkTokenRequest
	(*CreateLinkTokenResponse)(nil),     // 1: plaid.CreateLinkTokenResponse
	(*ExchangePublicTokenRequest)(nil),  // 2: plaid.ExchangePublicTokenRequest
	(*ExchangePublicTokenResponse)(nil), // 3: plaid.ExchangePublicTokenResponse
	(*GetAccountsRequest)(nil),          // 4: plaid.GetAccountsRequest
	(*BankAccount)(nil),                 // 5: plaid.BankAccount
	(*GetAccountsResponse)(nil),         // 6: plaid.GetAccountsResponse
	(*GetBalanceRequest)(nil),           // 7: plaid.GetBalanceRequest
	(*GetBalanceResponse)(nil),          // 8: plaid.GetBalanceResponse
}
var file_plaid_proto_depIdxs = []int32{
	5, // 0: plaid.GetAccountsResponse.accounts:type_name -> plaid.BankAccount
	0, // 1: plaid.PlaidService.CreateLinkToken:input_type -> plaid.CreateLinkTokenRequest
	2, // 2: plaid.PlaidService.ExchangePublicToken:input_type -> plaid.ExchangePublicTokenRequest
	4, // 3: plaid.PlaidService.GetAccounts:input_type -> plaid.GetAccountsRequest
	7, // 4: plaid.PlaidService.GetBalance:input_type -> plaid.GetBalanceRequest
	1, // 5: plaid.PlaidService.CreateLinkToken:output_type -> plaid.CreateLinkTokenResponse
	3, // 6: plaid.PlaidService.ExchangePublicToken:output_type -> plaid.ExchangePublicTokenResponse
	6, // 7: plaid.PlaidService.GetAccounts:output_type -> plaid.GetAccountsResponse
	8, // 8: plaid.PlaidService.GetBalance:output_type -> plaid.GetBalanceResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plaid_proto_init() }
func file_plaid_proto_init() {
	if File_plaid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plaid_proto_rawDesc), len(file_plaid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plaid_proto_goTypes,
		DependencyIndexes: file_plaid_proto_depIdxs,
		MessageInfos:      file_plaid_proto_msgTypes,
	}.Build()
	File_plaid_proto = out.File
	file_plaid_proto_goTypes = nil
	file_plaid_proto_depIdxs = nil
}
