// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/roundup.proto

package roundup

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoundupRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionAmount float64                `protobuf:"fixed64,2,opt,name=transaction_amount,json=transactionAmount,proto3" json:"transaction_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RoundupRequest) Reset() {
	*x = RoundupRequest{}
	mi := &file_proto_roundup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundupRequest) ProtoMessage() {}

func (x *RoundupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roundup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundupRequest.ProtoReflect.Descriptor instead.
func (*RoundupRequest) Descriptor() ([]byte, []int) {
	return file_proto_roundup_proto_rawDescGZIP(), []int{0}
}

func (x *RoundupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoundupRequest) GetTransactionAmount() float64 {
	if x != nil {
		return x.TransactionAmount
	}
	return 0
}

type RoundupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundupId     string                 `protobuf:"bytes,1,opt,name=roundup_id,json=roundupId,proto3" json:"roundup_id,omitempty"`
	AmountRounded float64                `protobuf:"fixed64,2,opt,name=amount_rounded,json=amountRounded,proto3" json:"amount_rounded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundupResponse) Reset() {
	*x = RoundupResponse{}
	mi := &file_proto_roundup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundupResponse) ProtoMessage() {}

func (x *RoundupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roundup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundupResponse.ProtoReflect.Descriptor instead.
func (*RoundupResponse) Descriptor() ([]byte, []int) {
	return file_proto_roundup_proto_rawDescGZIP(), []int{1}
}

func (x *RoundupResponse) GetRoundupId() string {
	if x != nil {
		return x.RoundupId
	}
	return ""
}

func (x *RoundupResponse) GetAmountRounded() float64 {
	if x != nil {
		return x.AmountRounded
	}
	return 0
}

var File_proto_roundup_proto protoreflect.FileDescriptor

const file_proto_roundup_proto_rawDesc = "" +
	"\n" +
	"\x13proto/roundup.proto\x12\aroundup\"X\n" +
	"\x0eRoundupRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12-\n" +
	"\x12transaction_amount\x18\x02 \x01(\x01R\x11transactionAmount\"W\n" +
	"\x0fRoundupResponse\x12\x1d\n" +
	"\n" +
	"roundup_id\x18\x01 \x01(\tR\troundupId\x12%\n" +
	"\x0eamount_rounded\x18\x02 \x01(\x01R\ramountRounded2Y\n" +
	"\x0eRoundupService\x12G\n" +
	"\x12RoundupTransaction\x12\x17.roundup.RoundupRequest\x1a\x18.roundup.RoundupResponseB\x18Z\x16untether/proto;roundupb\x06proto3"

var (
	file_proto_roundup_proto_rawDescOnce sync.Once
	file_proto_roundup_proto_rawDescData []byte
)

func file_proto_roundup_proto_rawDescGZIP() []byte {
	file_proto_roundup_proto_rawDescOnce.Do(func() {
		file_proto_roundup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_roundup_proto_rawDesc), len(file_proto_roundup_proto_rawDesc)))
	})
	return file_proto_roundup_proto_rawDescData
}

var file_proto_roundup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_roundup_proto_goTypes = []any{
	(*RoundupRequest)(nil),  // 0: roundup.RoundupRequest
	(*RoundupResponse)(nil), // 1: roundup.RoundupResponse
}
var file_proto_roundup_proto_depIdxs = []int32{
	0, // 0: roundup.RoundupService.RoundupTransaction:input_type -> roundup.RoundupRequest
	1, // 1: roundup.RoundupService.RoundupTransaction:output_type -> roundup.RoundupResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_roundup_proto_init() }
func file_proto_roundup_proto_init() {
	if File_proto_roundup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_roundup_proto_rawDesc), len(file_proto_roundup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_roundup_proto_goTypes,
		DependencyIndexes: file_proto_roundup_proto_depIdxs,
		MessageInfos:      file_proto_roundup_proto_msgTypes,
	}.Build()
	File_proto_roundup_proto = out.File
	file_proto_roundup_proto_goTypes = nil
	file_proto_roundup_proto_depIdxs = nil
}
